cc_library(
    name = "mars",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    copts = [
      "'-std=c++14'",
    ],
    linkopts = [
      "-lz",
    ],
    visibility = [
      "//visibility:public",
    ],
)
